AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PMP Question Service - Lambda with S3

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production
        S3_BUCKET_NAME: !Ref PMPQuestionBucket
        CUSTOM_AWS_REGION: !Ref AWS::Region

Resources:
  # S3 Bucket for storing questions
  PMPQuestionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "pmp-questions-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # Main Lambda Function (no API key required)
  PMPQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/api/lambda.lambdaHandler
      Description: PMP Question Service API Lambda Function
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowCredentials: false
          AllowHeaders:
            - "*"
          AllowMethods:
            - "*"
          AllowOrigins:
            - "*"
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PMPQuestionBucket
        - S3WritePolicy:
            BucketName: !Ref PMPQuestionBucket

Outputs:
  PMPQuestionFunction:
    Description: "PMP Question Service Lambda Function ARN"
    Value: !GetAtt PMPQuestionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  PMPQuestionApi:
    Description: "HTTP API endpoint URL for PMP Question Service"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
      
  PMPQuestionFunctionUrl:
    Description: "Lambda Function URL for PMP Question Service"
    Value: !GetAtt PMPQuestionFunctionUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-FunctionUrl"
      
  PMPQuestionBucketName:
    Description: "S3 Bucket for PMP Questions"
    Value: !Ref PMPQuestionBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"