AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PMP Question Service API - Lambda Only

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production
        API_KEY: pmp_service_key_2024
        S3_BUCKET_NAME: !Ref PMPQuestionBucket
        CUSTOM_AWS_REGION: !Ref AWS::Region

Resources:
  PMPQuestionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "pmp-question-service-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30

  PMPQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/api/lambda.lambdaHandler
      Description: PMP Question Service API Lambda Function
      # Simple HTTP API endpoint with no API Gateway customization
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PMPQuestionBucket
        - S3WritePolicy:
            BucketName: !Ref PMPQuestionBucket

Outputs:
  PMPQuestionFunction:
    Description: "PMP Question Service Lambda Function ARN"
    Value: !GetAtt PMPQuestionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  PMPQuestionApi:
    Description: "API Gateway endpoint URL for PMP Question Service"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
      
  PMPQuestionBucketName:
    Description: "S3 Bucket for PMP Questions"
    Value: !Ref PMPQuestionBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"